---
title: Smile's Innovation
email: thibault.milan@smile.eu
author: Smile Innovation
description: Innovation Department at Smile, working on computer vision, machine learning,
  artificial intelligence, IoT, and a lot of other amazing topics. We are pushing
  forward new tech and explore, investigate, find new use cases for our clients.
footer_legal_note: "&copy; 2019 Smile. We do not track you (yet) with any Analytics
  tools. If you want to report anything, please write to thibault.milan@smile.fr ."
baseurl: "/"
url: https://innovation.smile.eu
date_format: "%b %e, %Y"
twitter:
  username: groupesmile
  card: sumary
facebook:
  app_id: 
  publisher: 
  admins: 
logo: 
social:
  medium: smileinnovation
  youtube: 
  newsletter: 
webmaster_verifications:
  google: 
  bing: 
  alexa: 
  yandex: 
  baidu: 
lang: en_US
markdown: kramdown
sass:
  style: compressed
plugins:
- jekyll-feed
- jekyll-paginate
- jekyll-archives
- jekyll-gist
- jekyll-youtube
- jekyll-seo-tag
collections:
  videos:
    output: true
  demos:
    output: true
  projects:
    output: true
  quotes:
    output: false
atom:
  postDirs:
  - _videos
  - _demos
  - _projects
  - _quotes
exclude:
- vendor/bundle
- s3_website.yml
- README.md
- LICENSE
- Gemfile
- Gemfile.lock
