# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Smile's Innovation
email: thibault.milan@smile.eu
author: Smile Innovation
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
footer_legal_note: >-
  &copy; 2019 Smile. We do not track you (yet) with any Analytics tools.
  If you want to report anything, please write to thibault.milan@smile.fr .
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://innovation.smile.eu" # the base hostname & protocol for your site, e.g. http://example.com
date_format: "%b %e, %Y"

twitter:
    username : groupesmile
    card: sumary
facebook:
    app_id:
    publisher:
    admins:
logo:
social:
    medium: smileinnovation
    youtube:
    newsletter:
webmaster_verifications:
    google:
    bing:
    alexa:
    yandex:
    baidu:
lang: en_US

# Build settings
markdown: kramdown
sass:
    style: compressed
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-archives
  - jekyll-gist
  - jekyll-youtube
  - jekyll-seo-tag

# Collection configuration
collections:
    videos:
        output: true
    demos:
        output: true
    projects:
        output: true
    quotes:
        output: false

# Atom Related configuration
atom:
    postDirs:
        - _videos
        - _demos
        - _projects
        - _quotes

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
