---
label: Project / Demo
hide_body: false
display_field: title
fields:
- type: text
  name: title
  label: Project Name
  config:
    required: true
- type: datetime
  name: date
  label: Date
  config:
    required: true
  default: now
- type: text
  name: description
  label: Description
- name: image
  type: file
  config:
    maxSize: 250
  label: Image
- type: text
  name: author
  label: Author
  description: Use the your shortname, it will be matched with our data/members.yml
  config:
    required: true
- type: text
  name: lang
  label: Language
  config:
    required: true
  default: en
- type: text
  name: layout
  label: layout
  default: post
