---
label: Project / Demo
hide_body: false
display_field: title
fields:
- type: text
  name: title
  label: Project Name
  config:
    required: true
- name: description
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: false
    schema:
      format: markdown
  label: Description
- name: image
  type: file
  config:
    maxSize: 250
  label: Image
- name: author
  type: select
  default: []
  config:
    required: false
    options: []
    source:
      type: documents
      section: config
      file: _data/authors.yml
      path: 
  label: Author
- type: datetime
  name: date
  label: Date
  config:
    required: true
  default: now
- name: lang
  type: select
  default: en_EN
  config:
    required: true
    options:
    - fr_FR
    - en_EN
    source:
      type: simple
      section: 
      file: 
      path: 
  label: Language of this content
- type: text
  name: layout
  label: layout
  default: post
  hidden: true
pages:
- _demos/2019-04-19-asset-tracking-truck.markdown
- _demos/2019-04-19-live-tracking-with-computer-vision.markdown
- _demos/2019-04-19-multiplication-table-with-snips.markdown
- _demos/2019-04-19-talking-to-your-coffee-machine-with-snips.markdown
- _demos/2019-04-19-voice-commerce-with-magento--snips.markdown
