name:                            Jekyll site build & AWS deploy

on:
  push:
    branches:
    - master

jobs:
  build:
    name:                        Building website with Jekyll
    runs-on:                     ubuntu-latest

    steps:
    - name:                      Checkout out project
      uses:                      actions/checkout@v1
    - name:                      Set up Ruby 2.6
      uses:                      actions/setup-ruby@v1
      with:
        ruby-version:            2.6.x
    - name:                      Build website
      run:                       |
        gem install bundler
        bundle install --jobs 4 --retry 3
        bundle exec jekyll build
    - name:                      Upload artifact
      uses:                      actions/upload-artifact@v1.0.0
      with:
        name:                    generated_site
        path:                    _site

  deploy:
    name:                        Deploying to AWS
    needs:                       [build]
    runs-on:                     ubuntu-latest

    steps:
      - name:                    Checkout out project
        uses:                    actions/checkout@v1
      - name:                    Download artifact
        uses:                    actions/download-artifact@v1.0.0
        with:
          name:                  generated_site
          path:                  _site
      - name:                    Run AWS Cli to sync content
        uses:                    justinharringa/actions-s3_website@v1.0
        with:
          args:                  push --site $SOURCE_DIR
        env:
          S3_BUCKET:             ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'eu-west-1'   # optional: defaults to us-east-1
          SOURCE_DIR: '_site'      # optional: defaults to entire repository
          DEST_DIR: '/' # optional: default to bucket root
