name:                 Jekyll site build & AWS deploy

on:
  push:
    branches:
    - master


jobs:
  build:

    runs-on:          ubuntu-latest

    steps:
    - uses:           actions/checkout@v1
    - name:           Set up Ruby 2.6
      uses:           actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - name:           Build website
      run:            |
        gem install bundler
        bundle install --jobs 4 --retry 3
        bundle exec jekyll build
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: generated_site
        path: _site
  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v1.0.0
        with:
          name: generated_site
          path: _site
      - uses: actions/checkout@master
      - uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-east-1'   # optional: defaults to us-east-1
          SOURCE_DIR: '_site'      # optional: defaults to entire repository
          DEST_DIR: 'deploy_test' # optional: default to bucket root
