name:                 Jekyll install and site build

on:                   [push]

jobs:
  build:

    runs-on:          ubuntu-latest

    steps:
    - uses:           actions/checkout@v1
    - name:           Set up Ruby 2.6
      uses:           actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - name:           Build website
      run:            |
        gem install bundler
        bundle install --jobs 4 --retry 3
        bundle exec jekyll build
    - name:           Deploy to AWS
      uses:           actions/aws/cli@master$
      run:            |
      s3 cp _site s3://${{secret.AWS_S3_BUCKET}}/deploy_test --recursive
      with:
          secret:
          - ${{secret.AWS_ACCESS_KEY_ID}}
          - ${{secret.AWS_SECRET_ACCESS_KEY}}
